### ISSUE TITLE
dataverk init -i feiler med ValueError 'dataverk_s3' is not a valid BucketStorage

### ISSUE THREAD

**Issue by gorzan** [navikt/dataverk#114]
```
/home/G153850/projects/datapakke-arbeidsledighet $ dataverk-cli init -i
Skriv inn ønsket pakkenavn: arbeidsledighet
Do you want to create the datapackage (arbeidsledighet)? [y/n] y
dataverk-cli init completed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_init.py", line 29, in run
    self._create()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_init.py", line 40, in _create
    self._edit_package_metadata()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_init.py", line 90, in _edit_package_metadata
    package_metadata['path'] = self._determine_bucket_path()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_init.py", line 105, in _determine_bucket_path
    if BucketStorage(bucket_type) == BucketStorage.GITHUB:
  File "/usr/local/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/local/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'dataverk_s3' is not a valid BucketStorage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataverk-cli", line 11, in <module>
    load_entry_point('dataverk==0.0.17', 'console_scripts', 'dataverk-cli')()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_cli_entrypoint.py", line 46, in main
    dp.run()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_init.py", line 32, in run
    raise Exception(f'Klarte ikke generere datapakken {self._settings_store["package_name"]}')
Exception: Klarte ikke generere datapakken arbeidsledighet

```

**Comment by erikvatt** [comment]
not to be implemented
dataverk-cli removed
