### ISSUE TITLE
gcloud publish bug: no priv_key for gcloud in settings object

### ISSUE THREAD

**Issue by erikvatt** [navikt/dataverk#99]
Publishing package tester-med-ny-dv-versjon
The private_key field was not found in the service account info.
dataverk-cli publish completed
Traceback (most recent call last):
  File "/usr/local/bin/dataverk-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_cli_entrypoint.py", line 67, in main
    publish_datapackage()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_publish.py", line 95, in publish_datapackage
    datapackage.publish()
  File "/usr/local/lib/python3.6/site-packages/dataverk_cli/dataverk_publish.py", line 87, in publish
    self.package_settings["package_name"]))
  File "/usr/local/lib/python3.6/site-packages/dataverk/utils/publish_data.py", line 6, in upload_to_storage_bucket
    conn.upload_blob(os.path.join(dir_path, 'datapackage.json'), datapackage_key_prefix + 'datapackage.json')
  File "/usr/local/lib/python3.6/site-packages/dataverk/connectors/google_storage.py", line 72, in upload_blob
    blob = self.bucket.blob(destination_blob_name)
AttributeError: 'GoogleStorageConnector' object has no attribute 'bucket'

**Comment by erikvatt** [comment]
fungerer fra vdi, men ikke pod
